---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u2553504/public_html/
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='README.md' --exclude='*.zip' --exclude='.DS_Store' ./ $DEPLOYPATH
