---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u2553504/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH
    - /bin/cp send-mail.php $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R bootstrap-3.3.7 $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R phpmailer $DEPLOYPATH
